name: Code Quality

on: [push, pull_request]

jobs:
  core-tests:
    name: Core Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev
        pip install -r requirements.txt
    - name: Run core tests
      run: |
        pytest tests/core/ -v

  nlu-tests:
    name: NLU Tests  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev
        pip install -r requirements.txt
    - name: Run NLU tests
      run: |
        pytest tests/nlu/ -v

  hardware-tests:
    name: Hardware Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev
        pip install -r requirements.txt
    - name: Run hardware tests
      run: |
        pytest tests/hardware/ -v

  plugin-tests:
    name: Plugin Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev
        pip install -r requirements.txt
    - name: Run plugin tests
      run: |
        pytest tests/plugins/ -v

  backup-tests:
    name: Backup Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev
        pip install -r requirements.txt
    - name: Run backup tests
      run: |
        pytest tests/test_backup_scheduler.py -v