name: Documentation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - '**/*.md'
      - 'proxmox_nli/**/*.py'  # For docstrings
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - '**/*.md'
      - 'proxmox_nli/**/*.py'  # For docstrings

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev
        pip install -r requirements.txt
    - name: Run tests
      run: python -m unittest discover

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install mkdocs mkdocs-material mkdocstrings
          
      - name: Generate docs
        run: python autodoc.py
        
      - name: Deploy documentation
        run: mkdocs gh-deploy --force