name: Documentation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - '**/*.md'
      - 'proxmox_nli/**/*.py'  # For docstrings
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docs/**'
      - '**/*.md'
      - 'proxmox_nli/**/*.py'  # For docstrings

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install mkdocs mkdocs-material mkdocstrings pydocstyle
          
      - name: Check docstring style
        run: pydocstyle proxmox_nli/ --count
        continue-on-error: true
          
      - name: Build documentation
        run: |
          python autodoc.py
          mkdocs build
          
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: site/
          
  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install mkdocs mkdocs-material mkdocstrings
          
      - name: Generate docs
        run: python autodoc.py
        
      - name: Deploy documentation
        run: mkdocs gh-deploy --force